name: bloc_template_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  drift: ^2.20.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  slang: ^3.32.0
  slang_flutter: ^3.32.0
  sqlite3_flutter_libs: ^0.5.24
  supabase_flutter: ^2.8.0
  uuid: ^4.5.1
  vector_graphics: ^1.1.11+1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  mocktail: ^1.0.4
  slang_build_runner: ^3.32.0
  vector_graphics_compiler: ^1.1.11+1
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler
